In [71]:
import numpy as np
import pandas as pd

In [72]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placement'])
df

cgpa  profile_score  placement
0     8              8          1
1     7              9          1
2     6             10          0
3     5              5          0

In [73]:
def initialize_parameters(layer_dims):
  parameters = {}
  l = len(layer_dims)

  for i in range(1,l):
    parameters['w' + str(i)] = np.ones((layer_dims[i-1],layer_dims[i]))*0.1
    parameters['b' + str(i)] = np.zeros((layer_dims[i],1))

  return parameters


In [74]:
initialize_parameters([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [75]:
def forward(X,parameters):

  A = X
  l = len(parameters)//2

  for i in range(1,l+1):
    A_prev = A
    w = parameters['w' + str(i)]
    b = parameters['b' + str(i)]
    A = np.dot(w.T,A_prev) + b
    A = 1/(1+np.exp(-A))
    # A = A[0][0]
    # A = 1 if A > 0.5 else 0

  return A,A_prev

In [76]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.0001 * (y - y_hat))

  parameters['w1'][0][0] = parameters['w1'][0][0] + (0.0001 * (y - y_hat)*parameters['w2'][0][0]*A1[0][0]*(1 - A1[0][0])*X[0][0])
  parameters['w1'][0][1] = parameters['w1'][0][1] + (0.0001 * (y - y_hat)*parameters['w2'][0][0]*A1[0][0]*(1 - A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['w2'][0][0]*A1[0][0]*(1 - A1[0][0]))

  parameters['w1'][1][0] = parameters['w1'][1][0] + (0.0001 * (y - y_hat)*parameters['w2'][1][0]*A1[1][0]*(1 - A1[1][0])*X[0][0])
  parameters['w1'][1][1] = parameters['w1'][1][1] + (0.0001 * (y - y_hat)*parameters['w2'][1][0]*A1[1][0]*(1 - A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['w2'][1][0]*A1[1][0]*(1 - A1[1][0]))


In [77]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['placement']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

0.5415051895671072
Loss for this student -  0.613402628898913


In [78]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'w1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'w2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [79]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['placement']].values[1][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

0.5415051895671072
Loss for this student -  0.613402628898913


In [80]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'w1': array([[0.10000449, 0.10000577],
        [0.10000449, 0.10000577]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'w2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [81]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1)
y = df[['placement']].values[2][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

0.5415051895671072
Loss for this student -  0.7798063059256977


In [82]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'w1': array([[0.09999546, 0.09999244],
        [0.09999546, 0.09999244]]),
 'b1': array([[-7.56487203e-07],
        [-7.56487203e-07]]),
 'w2': array([[0.09995495],
        [0.09995495]]),
 'b2': array([[0.0999008]])}

In [83]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1)
y = df[['placement']].values[3][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

0.5364879492065946
Loss for this student -  0.768922894759937


In [84]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'w1': array([[0.09999473, 0.09999473],
        [0.09999473, 0.09999473]]),
 'b1': array([[-1.05438563e-06],
        [-1.05438563e-06]]),
 'w2': array([[0.09996078],
        [0.09996078]]),
 'b2': array([[0.09990713]])}

In [86]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placement']].values[j][0]

    # Parameter initialization


    y_hat,A1 = forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7103199085929446
Epoch -  2 Loss -  0.6991702892802629
Epoch -  3 Loss -  0.6991679314811485
Epoch -  4 Loss -  0.6991655746710999
Epoch -  5 Loss -  0.6991632188496667
Epoch -  6 Loss -  0.699160864016399
Epoch -  7 Loss -  0.6991585101708473
Epoch -  8 Loss -  0.6991561573125619
Epoch -  9 Loss -  0.6991538054410936
Epoch -  10 Loss -  0.6991514545559935
Epoch -  11 Loss -  0.6991491046568126
Epoch -  12 Loss -  0.6991467557431024
Epoch -  13 Loss -  0.6991444078144144
Epoch -  14 Loss -  0.6991420608703007
Epoch -  15 Loss -  0.6991397149103132
Epoch -  16 Loss -  0.6991373699340042
Epoch -  17 Loss -  0.6991350259409265
Epoch -  18 Loss -  0.6991326829306324
Epoch -  19 Loss -  0.6991303409026751
Epoch -  20 Loss -  0.699127999856608
Epoch -  21 Loss -  0.6991256597919842
Epoch -  22 Loss -  0.6991233207083575
Epoch -  23 Loss -  0.6991209826052818
Epoch -  24 Loss -  0.699118645482311
Epoch -  25 Loss -  0.6991163093389996
Epoch -  26 Loss -  0.699113974174902

{'w1': array([[0.09994267, 0.09984548],
        [0.09994272, 0.09984548]]),
 'b1': array([[-3.38405750e-05],
        [-3.38419977e-05]]),
 'w2': array([[0.09920806],
        [0.09920816]]),
 'b2': array([[0.09915209]])}

# Using Keras

In [105]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [106]:
model = Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [107]:
new_weights = [
    np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),

    np.array([0., 0.], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0.], dtype=np.float32)
]

In [108]:
model.set_weights(new_weights)
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [109]:
optimizer = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='binary_crossentropy')

In [110]:
model.fit(df.iloc[:,0:-1].values,df['placement'].values,epochs=50,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.6838  
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6837 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6826 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7170 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7325 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6716 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7303
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6561  
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7169 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6734 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6826 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7066 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7065 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6826 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7025 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━